# Generated by Django 5.1.6 on 2025-03-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('birth_date', models.DateField()),
                ('gifts', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Acquaintance', 'Acquaintance'), ('Friend', 'Friend'), ('Family', 'Family')], default='Friend', max_length=20)),
            ],
        ),
    ]
